version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Building and packaging Lambda function..."
      - sam build
      - sam package \
          --s3-bucket springimagesmohan \
          --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
