version: 0.2

phases:
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo "Tagging image..."
      - docker tag $ImageName:latest <your-ecr-uri>/$ImageName:latest
      - echo "Pushing image to ECR..."
      - docker push <your-ecr-uri>/$ImageName:latest
